#!/usr/bin/env python3
"""
Authoritative deterministic contract bindings generator for SIH26168.
Implements WP-01.4 as specified by Architecture Revision 3 Component C-20
and contracts/INTERFACE_SCHEMA_PLAN.md.

Produces deterministic native data models in C++20, Python, and Kotlin
from JSON Schema Draft 2020-12 and canonical enum contract definitions.
Adheres strictly to docs/GENERATED_FILE_POLICY.md.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List, Tuple

ROOT = Path(__file__).resolve().parents[1]
CONTRACTS_DIR = ROOT / "contracts"
ENUMS_DIR = CONTRACTS_DIR / "enums"
SCHEMAS_DIR = CONTRACTS_DIR / "schemas/common"
VERSION_FILE = CONTRACTS_DIR / "VERSION"
GENERATED_DIR = CONTRACTS_DIR / "generated"

GENERATOR_VERSION = "1.0.0-bootstrap"
COMMAND_TAG = "python ci/generate_contract_bindings.py"


def get_contract_version() -> str:
    if VERSION_FILE.is_file():
        return VERSION_FILE.read_text(encoding="utf-8").strip()
    return "1.0.0-bootstrap"


def make_header(sources: str, comment_prefix: str = "//") -> str:
    return (
        f"{comment_prefix} Auto-generated by ci/generate_contract_bindings.py. DO NOT EDIT.\n"
        f"{comment_prefix} Source schemas: {sources}\n"
        f"{comment_prefix} Generator version: {GENERATOR_VERSION}\n"
        f"{comment_prefix} Deterministic command: {COMMAND_TAG}\n\n"
    )


def load_enums() -> Dict[str, Dict]:
    enums = {}
    for p in sorted(ENUMS_DIR.glob("*.json")):
        data = json.loads(p.read_text(encoding="utf-8"))
        enums[p.name] = data
    return enums


def load_schemas() -> Dict[str, Dict]:
    schemas = {}
    for p in sorted(SCHEMAS_DIR.glob("*.json")):
        data = json.loads(p.read_text(encoding="utf-8"))
        schemas[p.name] = data
    return schemas


def collect_input_paths() -> List[str]:
    inputs = [VERSION_FILE.relative_to(ROOT).as_posix()]
    for p in sorted(ENUMS_DIR.glob("*.json")):
        inputs.append(p.relative_to(ROOT).as_posix())
    for p in sorted(SCHEMAS_DIR.glob("*.json")):
        inputs.append(p.relative_to(ROOT).as_posix())
    return sorted(inputs)


def generate_contract_version_manifest(version: str, inputs: List[str]) -> str:
    data = {
        "contract_version": version,
        "generated_from": inputs,
    }
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


def generate_cpp_enums(enums: Dict[str, Dict]) -> str:
    out = make_header("contracts/enums/*.json", "//")
    out += "#pragma once\n\n"
    out += "#include <cstdint>\n"
    out += "#include <optional>\n"
    out += "#include <string_view>\n\n"
    out += "namespace sih26168::contracts {\n\n"

    # Enums to generate
    enum_list: List[Tuple[str, List[str]]] = []
    for filename, data in sorted(enums.items()):
        name = data.get("enum_name")
        if name and "values" in data:
            enum_list.append((name, data["values"]))
        elif filename == "navigation_states_v1.json":
            if "provenance" in data:
                enum_list.append(("ProvenanceClassificationV1", data["provenance"]))

    # Also add ProvenanceTypeV1 from common provenance schema if not already present
    if not any(name == "ProvenanceTypeV1" for name, _ in enum_list):
        enum_list.append(("ProvenanceTypeV1", ["LIVE_DEVICE", "DETERMINISTIC_REPLAY", "LIVE", "REPLAY"]))

    for enum_name, values in sorted(enum_list, key=lambda x: x[0]):
        out += f"enum class {enum_name} : uint8_t {{\n"
        for v in values:
            out += f"    {v},\n"
        out += "};\n\n"

        # to_string
        out += f"[[nodiscard]] constexpr std::string_view to_string({enum_name} value) noexcept {{\n"
        out += "    switch (value) {\n"
        for v in values:
            out += f'        case {enum_name}::{v}: return "{v}";\n'
        out += '        default: return "UNKNOWN";\n'
        out += "    }\n"
        out += "}\n\n"

        # parse
        out += f"[[nodiscard]] constexpr std::optional<{enum_name}> parse_{enum_name}(std::string_view str) noexcept {{\n"
        for v in values:
            out += f'    if (str == "{v}") return {enum_name}::{v};\n'
        out += "    return std::nullopt;\n"
        out += "}\n\n"

    out += "} // namespace sih26168::contracts\n"
    return out


def generate_cpp_models() -> str:
    out = make_header("contracts/schemas/common/*.schema.json", "//")
    out += "#pragma once\n\n"
    out += "#include <cstdint>\n"
    out += "#include <optional>\n"
    out += "#include <string>\n"
    out += "#include <vector>\n"
    out += '#include "enums.hpp"\n\n'
    out += "namespace sih26168::contracts {\n\n"

    out += "struct TimestampV1 {\n"
    out += "    uint64_t epoch_ns{0};\n"
    out += "    uint64_t arrival_elapsed_realtime_ns{0};\n"
    out += "    std::optional<uint64_t> source_timestamp_ns{std::nullopt};\n"
    out += "    std::string clock_id{};\n"
    out += "};\n\n"

    out += "struct ProvenanceV1 {\n"
    out += "    std::string evidence_id{};\n"
    out += "    std::string session_id{};\n"
    out += "    std::string stream_id{};\n"
    out += "    std::optional<std::string> device_id{std::nullopt};\n"
    out += "    std::optional<std::string> build_id{std::nullopt};\n"
    out += "    ProvenanceTypeV1 provenance_type{ProvenanceTypeV1::LIVE_DEVICE};\n"
    out += "    bool synthetic{false};\n"
    out += "    std::vector<std::string> contributing_evidence_ids{};\n"
    out += "};\n\n"

    out += "struct ValidityGateV1 {\n"
    out += "    bool is_finite{true};\n"
    out += "    bool is_valid{true};\n"
    out += "    uint32_t flags{0};\n"
    out += "    std::optional<std::string> rejection_code{std::nullopt};\n"
    out += "};\n\n"

    out += "struct EvidenceEnvelopeV1 {\n"
    out += "    uint32_t schema_version{1};\n"
    out += "    std::string payload_type{};\n"
    out += "    TimestampV1 timestamp{};\n"
    out += "    ProvenanceV1 provenance{};\n"
    out += "    ValidityGateV1 validity_gate{};\n"
    out += "};\n\n"

    out += "} // namespace sih26168::contracts\n"
    return out


def generate_python_enums(enums: Dict[str, Dict]) -> str:
    out = make_header("contracts/enums/*.json", "#")
    out += "from enum import Enum\n\n"

    enum_list: List[Tuple[str, List[str]]] = []
    for filename, data in sorted(enums.items()):
        name = data.get("enum_name")
        if name and "values" in data:
            enum_list.append((name, data["values"]))
        elif filename == "navigation_states_v1.json":
            if "provenance" in data:
                enum_list.append(("ProvenanceClassificationV1", data["provenance"]))

    if not any(name == "ProvenanceTypeV1" for name, _ in enum_list):
        enum_list.append(("ProvenanceTypeV1", ["LIVE_DEVICE", "DETERMINISTIC_REPLAY", "LIVE", "REPLAY"]))

    for enum_name, values in sorted(enum_list, key=lambda x: x[0]):
        out += f"class {enum_name}(str, Enum):\n"
        for v in values:
            out += f'    {v} = "{v}"\n'
        out += "\n\n"

    return out.rstrip() + "\n"


def generate_python_models() -> str:
    out = make_header("contracts/schemas/common/*.schema.json", "#")
    out += "from __future__ import annotations\n\n"
    out += "from dataclasses import dataclass, field\n"
    out += "from typing import Any, Dict, List, Optional\n\n"
    out += "from .enums import ProvenanceTypeV1\n\n\n"

    out += "@dataclass(frozen=True)\n"
    out += "class TimestampV1:\n"
    out += "    epoch_ns: int\n"
    out += "    arrival_elapsed_realtime_ns: int\n"
    out += "    clock_id: str\n"
    out += "    source_timestamp_ns: Optional[int] = None\n\n"
    out += "    def to_dict(self) -> Dict[str, Any]:\n"
    out += "        res: Dict[str, Any] = {\n"
    out += '            "epoch_ns": self.epoch_ns,\n'
    out += '            "arrival_elapsed_realtime_ns": self.arrival_elapsed_realtime_ns,\n'
    out += '            "clock_id": self.clock_id,\n'
    out += "        }\n"
    out += "        if self.source_timestamp_ns is not None:\n"
    out += '            res["source_timestamp_ns"] = self.source_timestamp_ns\n'
    out += "        return res\n\n"
    out += "    @classmethod\n"
    out += "    def from_dict(cls, data: Dict[str, Any]) -> TimestampV1:\n"
    out += "        return cls(\n"
    out += '            epoch_ns=int(data["epoch_ns"]),\n'
    out += '            arrival_elapsed_realtime_ns=int(data["arrival_elapsed_realtime_ns"]),\n'
    out += '            clock_id=str(data["clock_id"]),\n'
    out += '            source_timestamp_ns=data.get("source_timestamp_ns"),\n'
    out += "        )\n\n\n"

    out += "@dataclass(frozen=True)\n"
    out += "class ProvenanceV1:\n"
    out += "    evidence_id: str\n"
    out += "    session_id: str\n"
    out += "    stream_id: str\n"
    out += "    provenance_type: ProvenanceTypeV1 = ProvenanceTypeV1.LIVE_DEVICE\n"
    out += "    synthetic: bool = False\n"
    out += "    device_id: Optional[str] = None\n"
    out += "    build_id: Optional[str] = None\n"
    out += "    contributing_evidence_ids: List[str] = field(default_factory=list)\n\n"
    out += "    def to_dict(self) -> Dict[str, Any]:\n"
    out += "        res: Dict[str, Any] = {\n"
    out += '            "evidence_id": self.evidence_id,\n'
    out += '            "session_id": self.session_id,\n'
    out += '            "stream_id": self.stream_id,\n'
    out += '            "provenance_type": self.provenance_type.value if hasattr(self.provenance_type, "value") else str(self.provenance_type),\n'
    out += '            "synthetic": self.synthetic,\n'
    out += '            "contributing_evidence_ids": list(self.contributing_evidence_ids),\n'
    out += "        }\n"
    out += "        if self.device_id is not None:\n"
    out += '            res["device_id"] = self.device_id\n'
    out += "        if self.build_id is not None:\n"
    out += '            res["build_id"] = self.build_id\n'
    out += "        return res\n\n"
    out += "    @classmethod\n"
    out += "    def from_dict(cls, data: Dict[str, Any]) -> ProvenanceV1:\n"
    out += "        return cls(\n"
    out += '            evidence_id=str(data["evidence_id"]),\n'
    out += '            session_id=str(data["session_id"]),\n'
    out += '            stream_id=str(data["stream_id"]),\n'
    out += '            provenance_type=ProvenanceTypeV1(data["provenance_type"]),\n'
    out += '            synthetic=bool(data.get("synthetic", False)),\n'
    out += '            device_id=data.get("device_id"),\n'
    out += '            build_id=data.get("build_id"),\n'
    out += '            contributing_evidence_ids=list(data.get("contributing_evidence_ids", [])),\n'
    out += "        )\n\n\n"

    out += "@dataclass(frozen=True)\n"
    out += "class ValidityGateV1:\n"
    out += "    is_finite: bool = True\n"
    out += "    is_valid: bool = True\n"
    out += "    flags: int = 0\n"
    out += "    rejection_code: Optional[str] = None\n\n"
    out += "    def to_dict(self) -> Dict[str, Any]:\n"
    out += "        res: Dict[str, Any] = {\n"
    out += '            "is_finite": self.is_finite,\n'
    out += '            "is_valid": self.is_valid,\n'
    out += '            "flags": self.flags,\n'
    out += "        }\n"
    out += "        if self.rejection_code is not None:\n"
    out += '            res["rejection_code"] = self.rejection_code\n'
    out += "        return res\n\n"
    out += "    @classmethod\n"
    out += "    def from_dict(cls, data: Dict[str, Any]) -> ValidityGateV1:\n"
    out += "        return cls(\n"
    out += '            is_finite=bool(data.get("is_finite", True)),\n'
    out += '            is_valid=bool(data.get("is_valid", True)),\n'
    out += '            flags=int(data.get("flags", 0)),\n'
    out += '            rejection_code=data.get("rejection_code"),\n'
    out += "        )\n\n\n"

    out += "@dataclass(frozen=True)\n"
    out += "class EvidenceEnvelopeV1:\n"
    out += "    payload_type: str\n"
    out += "    timestamp: TimestampV1\n"
    out += "    provenance: ProvenanceV1\n"
    out += "    payload: Dict[str, Any]\n"
    out += "    validity_gate: ValidityGateV1\n"
    out += "    schema_version: int = 1\n\n"
    out += "    def to_dict(self) -> Dict[str, Any]:\n"
    out += "        return {\n"
    out += '            "schema_version": self.schema_version,\n'
    out += '            "payload_type": self.payload_type,\n'
    out += '            "timestamp": self.timestamp.to_dict(),\n'
    out += '            "provenance": self.provenance.to_dict(),\n'
    out += '            "payload": self.payload,\n'
    out += '            "validity_gate": self.validity_gate.to_dict(),\n'
    out += "        }\n\n"
    out += "    @classmethod\n"
    out += "    def from_dict(cls, data: Dict[str, Any]) -> EvidenceEnvelopeV1:\n"
    out += "        return cls(\n"
    out += '            schema_version=int(data.get("schema_version", 1)),\n'
    out += '            payload_type=str(data["payload_type"]),\n'
    out += '            timestamp=TimestampV1.from_dict(data["timestamp"]),\n'
    out += '            provenance=ProvenanceV1.from_dict(data["provenance"]),\n'
    out += '            payload=dict(data["payload"]),\n'
    out += '            validity_gate=ValidityGateV1.from_dict(data["validity_gate"]),\n'
    out += "        )\n"

    return out.rstrip() + "\n"


def generate_python_init() -> str:
    out = make_header("contracts/schemas/common/*.json", "#")
    out += "from .enums import (\n"
    out += "    AlignmentStatusV1,\n"
    out += "    DisplayModeV1,\n"
    out += "    HealthIntegrityStateV1,\n"
    out += "    MapStatusV1,\n"
    out += "    ModelStatusV1,\n"
    out += "    NavigationModeV1,\n"
    out += "    ProvenanceClassificationV1,\n"
    out += "    ProvenanceTypeV1,\n"
    out += "    ReacquisitionStatusV1,\n"
    out += "    RecordingStatusV1,\n"
    out += "    SensorStatusV1,\n"
    out += ")\n"
    out += "from .models import (\n"
    out += "    EvidenceEnvelopeV1,\n"
    out += "    ProvenanceV1,\n"
    out += "    TimestampV1,\n"
    out += "    ValidityGateV1,\n"
    out += ")\n\n"
    out += "__all__ = [\n"
    out += '    "AlignmentStatusV1",\n'
    out += '    "DisplayModeV1",\n'
    out += '    "HealthIntegrityStateV1",\n'
    out += '    "MapStatusV1",\n'
    out += '    "ModelStatusV1",\n'
    out += '    "NavigationModeV1",\n'
    out += '    "ProvenanceClassificationV1",\n'
    out += '    "ProvenanceTypeV1",\n'
    out += '    "ReacquisitionStatusV1",\n'
    out += '    "RecordingStatusV1",\n'
    out += '    "SensorStatusV1",\n'
    out += '    "TimestampV1",\n'
    out += '    "ProvenanceV1",\n'
    out += '    "ValidityGateV1",\n'
    out += '    "EvidenceEnvelopeV1",\n'
    out += "]\n"
    return out


def generate_kotlin_enums(enums: Dict[str, Dict]) -> str:
    out = make_header("contracts/enums/*.json", "//")
    out += "package org.sih26168.contracts.enums\n\n"

    enum_list: List[Tuple[str, List[str]]] = []
    for filename, data in sorted(enums.items()):
        name = data.get("enum_name")
        if name and "values" in data:
            enum_list.append((name, data["values"]))
        elif filename == "navigation_states_v1.json":
            if "provenance" in data:
                enum_list.append(("ProvenanceClassificationV1", data["provenance"]))

    if not any(name == "ProvenanceTypeV1" for name, _ in enum_list):
        enum_list.append(("ProvenanceTypeV1", ["LIVE_DEVICE", "DETERMINISTIC_REPLAY", "LIVE", "REPLAY"]))

    for enum_name, values in sorted(enum_list, key=lambda x: x[0]):
        out += f"enum class {enum_name} {{\n"
        for v in values:
            out += f"    {v},\n"
        out += "}\n\n"

    return out.rstrip() + "\n"


def generate_kotlin_models() -> str:
    out = make_header("contracts/schemas/common/*.schema.json", "//")
    out += "package org.sih26168.contracts.models\n\n"
    out += "import org.sih26168.contracts.enums.ProvenanceTypeV1\n\n"

    out += "data class TimestampV1(\n"
    out += "    val epochNs: Long,\n"
    out += "    val arrivalElapsedRealtimeNs: Long,\n"
    out += "    val clockId: String,\n"
    out += "    val sourceTimestampNs: Long? = null\n"
    out += ")\n\n"

    out += "data class ProvenanceV1(\n"
    out += "    val evidenceId: String,\n"
    out += "    val sessionId: String,\n"
    out += "    val streamId: String,\n"
    out += "    val provenanceType: ProvenanceTypeV1 = ProvenanceTypeV1.LIVE_DEVICE,\n"
    out += "    val synthetic: Boolean = false,\n"
    out += "    val deviceId: String? = null,\n"
    out += "    val buildId: String? = null,\n"
    out += "    val contributingEvidenceIds: List<String> = emptyList()\n"
    out += ")\n\n"

    out += "data class ValidityGateV1(\n"
    out += "    val isFinite: Boolean = true,\n"
    out += "    val isValid: Boolean = true,\n"
    out += "    val flags: Long = 0L,\n"
    out += "    val rejectionCode: String? = null\n"
    out += ")\n\n"

    out += "data class EvidenceEnvelopeV1<T>(\n"
    out += "    val schemaVersion: Int = 1,\n"
    out += "    val payloadType: String,\n"
    out += "    val timestamp: TimestampV1,\n"
    out += "    val provenance: ProvenanceV1,\n"
    out += "    val payload: T,\n"
    out += "    val validityGate: ValidityGateV1\n"
    out += ")\n"

    return out


def generate_all_bindings() -> Dict[Path, str]:
    version = get_contract_version()
    enums = load_enums()
    schemas = load_schemas()
    inputs = collect_input_paths()

    bindings: Dict[Path, str] = {}

    # 1. Manifest
    bindings[GENERATED_DIR / "contract_version.json"] = generate_contract_version_manifest(version, inputs)

    # 2. C++
    bindings[GENERATED_DIR / "cpp/enums.hpp"] = generate_cpp_enums(enums)
    bindings[GENERATED_DIR / "cpp/models.hpp"] = generate_cpp_models()

    # 3. Python
    bindings[GENERATED_DIR / "python/__init__.py"] = generate_python_init()
    bindings[GENERATED_DIR / "python/enums.py"] = generate_python_enums(enums)
    bindings[GENERATED_DIR / "python/models.py"] = generate_python_models()

    # 4. Kotlin
    bindings[GENERATED_DIR / "kotlin/Enums.kt"] = generate_kotlin_enums(enums)
    bindings[GENERATED_DIR / "kotlin/Models.kt"] = generate_kotlin_models()

    return bindings


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Deterministic contract bindings generator for C++, Python, and Kotlin."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check on-disk generated bindings against expected output; exits with non-zero on drift.",
    )
    args = parser.parse_args()

    expected_bindings = generate_all_bindings()

    if args.check:
        drift_errors = []
        for path, expected_content in sorted(expected_bindings.items(), key=lambda x: str(x[0])):
            rel_path = path.relative_to(ROOT).as_posix()
            if not path.is_file():
                drift_errors.append(f"missing generated file: {rel_path}")
            else:
                actual_content = path.read_text(encoding="utf-8")
                if actual_content != expected_content:
                    drift_errors.append(f"drift in generated file: {rel_path}")

        if drift_errors:
            sys.stderr.write("Generated contract bindings drift detected:\n")
            for err in drift_errors:
                sys.stderr.write(f"  - {err}\n")
            sys.exit(1)

        print("PASS: generated contract bindings")
        return 0

    # Generation mode
    for path, content in expected_bindings.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")

    print(f"PASS: successfully generated {len(expected_bindings)} contract binding artifacts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
